# Generated by Django 2.2.7 on 2019-11-05 11:30

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=apps.core.fields.AutoSlugField(max_length=250),
        ),
    ]
